import { test, expect } from '@playwright/test';

// Reusable long timeout value (can be configured via TIMEOUT_NAVIGATION env var)
const LONG_TIMEOUT = parseInt(process.env.TIMEOUT_NAVIGATION ?? '60000');

test.describe('AI Calendar Helper Workflow', () => {
  test.beforeEach(async ({ page }) => {
    // Mock the OpenAI API call to avoid real API charges
    await page.route('**/api/ai/parse-events', async route => {
      const request = route.request();
      const postData = request.postDataJSON();

      // Create mock response that matches the actual API format
      const inputText = postData.text || '';
      const mockResponse = {
        success: true,
        events: [
          {
            id: 'test-event-1',
            title: inputText.includes('meeting') ? 'Team Meeting' : 'Sample Event',
            description: 'Generated by AI processing',
            startDate: '2025-06-12T20:00:00.000Z', // 8PM UTC = 4PM Eastern
            endDate: '2025-06-12T21:00:00.000Z', // 9PM UTC = 5PM Eastern
            location:
              inputText.includes('conference') || inputText.includes('room')
                ? 'Conference Room A'
                : '',
            timezone: 'America/New_York',
            confidence: 0.88,
            isAllDay: false,
            recurrence: null,
          },
        ],
        processingTimeMs: 2500,
      };

      // Simulate realistic processing delay
      await new Promise(resolve => setTimeout(resolve, 1000));

      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(mockResponse),
      });
    });
  });

  test('should process event text and display parsed results', async ({ page }) => {
    // Navigate to Calendar Parser page
    await page.goto('/calendar-parser');

    // Verify page loaded
    await expect(page.getByRole('heading', { name: 'Calendar Parser' })).toBeVisible();

    // Find the text input area (not in the Raw JSON debug area)
    const textInput = page.locator('textarea[placeholder*="Enter your event text"]');
    await expect(textInput).toBeVisible();

    // Enter event text
    const eventText = 'Team meeting tomorrow at 2pm in the conference room';
    await textInput.fill(eventText);

    // Find and click the Parse Events button
    const parseButton = page.getByRole('button', { name: /parse events/i });
    await expect(parseButton).toBeEnabled();
    await parseButton.click();

    // Wait for results to appear - check for either success or error
    await expect(page.locator('h2:has-text("Found"), h2:has-text("Error")')).toBeVisible({
      timeout: 10000,
    });

    // Verify at least one event card rendered with calendar integration buttons
    await expect(
      page.locator('[data-testid="calendar-integration-buttons"]').first()
    ).toBeVisible();

    // Verify form is re-enabled after processing
    await expect(parseButton).toBeEnabled();
    await expect(textInput).toBeEnabled();
    await expect(page.getByRole('button', { name: /clear/i })).toBeEnabled();
  });

  test('should handle API errors gracefully', async ({ page }) => {
    // Mock API error
    await page.route('**/api/ai/parse-events', async route => {
      await route.fulfill({
        status: 500,
        contentType: 'application/json',
        body: JSON.stringify({
          error: 'AI service temporarily unavailable',
        }),
      });
    });

    await page.goto('/calendar-parser');

    const textInput = page.locator('textarea[placeholder*="Enter your event text"]');
    await textInput.fill('Meeting tomorrow');

    const parseButton = page.getByRole('button', { name: /parse events/i });
    await parseButton.click();

    // Wait for error indication (heading or alert)
    await expect(page.locator('h2:has-text("Error"), [role="alert"]')).toBeVisible({
      timeout: 12000,
    });

    // Form should be usable again
    await expect(parseButton).toBeEnabled();
    await expect(textInput).toBeEnabled();
  });

  test('should validate required input', async ({ page }) => {
    await page.goto('/calendar-parser');

    const parseButton = page.getByRole('button', { name: /parse events/i });

    // Button should be disabled when no text
    await expect(parseButton).toBeDisabled();

    // Add text to enable button
    const textInput = page.locator('textarea[placeholder*="Enter your event text"]');
    await textInput.fill('Test event');
    await expect(parseButton).toBeEnabled();

    // Clear text to disable button again
    await textInput.fill('');
    await expect(parseButton).toBeDisabled();
  });

  test('should clear form when Clear button is clicked', async ({ page }) => {
    await page.goto('/calendar-parser');

    const textInput = page.locator('textarea[placeholder*="Enter your event text"]');
    const clearButton = page.getByRole('button', { name: /clear/i });

    // Fill text
    await textInput.fill('Some event text');
    await expect(textInput).toHaveValue('Some event text');

    // Click clear
    await clearButton.click();
    await expect(textInput).toHaveValue('');
  });

  test('should process complex event with all details', async ({ page }) => {
    // Mock detailed response
    await page.route('**/api/ai/parse-events', async route => {
      const mockResponse = {
        success: true,
        events: [
          {
            id: 'detailed-event-1',
            title: 'Annual Company Retreat',
            description: 'Three-day team building event with outdoor activities',
            startDate: '2025-07-15T13:00:00.000Z', // 1PM UTC = 9AM Eastern
            endDate: '2025-07-17T21:00:00.000Z', // 9PM UTC = 5PM Eastern
            location: 'Mountain View Resort, Lake Tahoe',
            timezone: 'America/Los_Angeles',
            confidence: 0.92,
            isAllDay: false,
            recurrence: null,
          },
        ],
        processingTimeMs: 4100,
      };

      await new Promise(resolve => setTimeout(resolve, 1200));
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(mockResponse),
      });
    });

    await page.goto('/calendar-parser');

    const textInput = page.locator('textarea[placeholder*="Enter your event text"]');
    await textInput.fill(
      'Annual company retreat from July 15-17 at Mountain View Resort in Lake Tahoe, includes team building activities'
    );

    const parseButton = page.getByRole('button', { name: /parse events/i });
    await parseButton.click();

    // Wait for complex event to be processed - check for either success or error
    await expect(page.locator('h2:has-text("Found"), h2:has-text("Error")')).toBeVisible({
      timeout: 15000,
    });

    // Verify all details using specific selectors to avoid conflicts
    await expect(page.getByRole('heading', { name: 'Annual Company Retreat' })).toBeVisible();
    await expect(page.getByText(/Confidence: 92%/)).toBeVisible();

    // Use specific paragraph selector for location to avoid input and debug conflicts
    const locationParagraph = page.locator('p', { hasText: '📍 Mountain View Resort, Lake Tahoe' });
    await expect(locationParagraph).toBeVisible();

    // Verify timing details
    await expect(page.locator('p', { hasText: /July 15, 2025/ })).toBeVisible();
  });

  test('should maintain form state during navigation', async ({ page }) => {
    await page.goto('/calendar-parser');

    const textInput = page.locator('textarea[placeholder*="Enter your event text"]');
    await textInput.fill('Test meeting content');

    // Navigate away and back
    await page.goto('/profile', { timeout: LONG_TIMEOUT });
    await page.goto('/calendar-parser', { timeout: LONG_TIMEOUT });

    // Re-select textarea to ensure fresh reference after navigation
    const newTextInput = page.locator('textarea[placeholder*="Enter your event text"]');
    await expect(newTextInput).toBeVisible({ timeout: LONG_TIMEOUT });

    // Form should be reset (this is expected behavior)
    await expect(newTextInput).toHaveValue('');
  });
});
